[tool.poetry]
name = "innohassle-events"
version = "0.1.0"
description = ""
authors = ["Ruslan Bel'kov <ruslan.belckov@yandex.ru>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "~3.11"
pydantic = "^2.6.1"
fastapi = {extras = ["all"], version = "^0.110.0"}
authlib = "^1.2.1"
cryptography = "^42.0.5"
icalendar = "^5.0.7"
aiofiles = "^23.1.0"
sqlalchemy = { extras = ["asyncpg"], version = "^2.0.25" }
asyncpg = "^0.29.0"
alembic = "^1.12.0"
pyyaml = "^6.0.1"
uvicorn = "^0.27.1"

[tool.poetry.group.prod]
optional = true
[tool.poetry.group.prod.dependencies]
gunicorn = "20.1.0"

[tool.poetry.group.code-style]
optional = true
[tool.poetry.group.code-style.dependencies]
ruff = "^0.2.2"
pre-commit = "^3.6.2"

[tool.poetry.group.test]
optional = true
[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
pytest-cov = "^4.1.0"
faker = "^18.13.0"

[tool.pytest.ini_options]
pythonpath = "."
testpaths = "tests"
addopts = [
    "--strict-config",
    "--strict-markers",
]

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
[tool.coverage.run]
omit = [
    "src/dev.py"
]
[tool.coverage.report]
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if enabled:",
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",
    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
    # Don't complain about TYPE_CHECKING imports:
    "if TYPE_CHECKING:",
]

ignore_errors = true
